from typing import Any, Optional, cast
from .models import FunctionDefinition


TOKEN_CACHE: dict[int, tuple[dict[str, int], set[int]]] = {}


def get_input_ids(text: str, model: Any) -> list[int]:
    """Encode text into token IDs.

    Args:
        text: Text to encode.
        model: LLM wrapper used for tokenization.

    Returns:
        Token IDs representing the text.
    """
    return cast(list[int], model.encode(text)[0].tolist())


def get_logits_from_text(
        text: str,
        model: Any,
) -> list[float]:
    """Get next-token logits for a text prompt.

    Args:
        text: Text prompt used as model context.
        model: LLM wrapper used for inference.

    Returns:
        Logit scores for every token in the model vocabulary.
    """
    return cast(
        list[float],
        model.get_logits_from_input_ids(get_input_ids(text, model)),
    )


def choose_next_token_id(
        logits: list[float],
        allowed: Optional[list[int]] = None,
) -> int:
    """Choose the highest-scoring token ID.

    Args:
        logits: Logit scores indexed by token ID.
        allowed: Optional token IDs allowed for selection.

    Returns:
        Token ID with the highest score among the allowed tokens.
    """
    if allowed:
        return max(allowed, key=lambda token_id: logits[token_id])
    return max(range(len(logits)), key=logits.__getitem__)


def get_vocabulary_size(model: Any) -> int:
    """Get the model vocabulary size.

    Args:
        model: LLM wrapper used for inference.

    Returns:
        Number of tokens in the model vocabulary.
    """
    return len(model.get_logits_from_input_ids(get_input_ids("a", model)))


def build_digit_tokens(
        model: Any,
        vocabulary_size: int,
) -> dict[str, int]:
    """Map single numeric characters to their token IDs.

    Args:
        model: LLM wrapper used for token decoding.
        vocabulary_size: Number of tokens in the model vocabulary.

    Returns:
        Mapping between numeric characters and token IDs.
    """
    characters = "0123456789.-+"
    return {
        text: token_id
        for token_id in range(vocabulary_size)
        if (text := model.decode([token_id])) in characters
    }


def build_quote_tokens(
        model: Any,
        vocabulary_size: int,
) -> set[int]:
    """Collect token IDs that contain a quote character.

    Args:
        model: LLM wrapper used for token decoding.
        vocabulary_size: Number of tokens in the model vocabulary.

    Returns:
        Token IDs whose decoded text contains a double quote.
    """
    return {
        token_id
        for token_id in range(vocabulary_size)
        if '"' in model.decode([token_id])
    }


def get_generation_tokens(
        model: Any,
) -> tuple[dict[str, int], set[int]]:
    """Get cached token groups used by constrained generation.

    Args:
        model: LLM wrapper used for tokenization and inference.

    Returns:
        Digit token mapping and quote token IDs.
    """
    model_key = id(model)
    if model_key not in TOKEN_CACHE:
        vocabulary_size = get_vocabulary_size(model)
        TOKEN_CACHE[model_key] = (
            build_digit_tokens(model, vocabulary_size),
            build_quote_tokens(model, vocabulary_size),
        )

    return TOKEN_CACHE[model_key]


def get_allowed_number_characters(generated: list[str]) -> set[str]:
    """Get valid next characters for a number.

    Args:
        generated: Number characters generated so far.

    Returns:
        Characters that can validly continue the number.
    """
    digits = set("0123456789")

    if not generated:
        return digits | {".", "-", "+"}

    allowed = set(digits)
    if "." not in generated:
        allowed.add(".")
    return allowed


def parse_generated_number(text: str) -> int | float:
    """Parse generated numeric text into a Python number.

    Args:
        text: Numeric text generated by the model.

    Returns:
        Parsed integer or float.
    """
    clean_text = text.strip()
    if "." in clean_text:
        return float(clean_text)
    return int(clean_text)


def generate_number(
        model: Any,
        context_ids: list[int],
        digit_tokens: dict[str, int],
        max_length: int = 20,
) -> int | float:
    """Generate a JSON number using constrained decoding.

    Args:
        model: LLM wrapper used for inference.
        context_ids: Token IDs that appear before the number.
        digit_tokens: Mapping between numeric characters and token IDs.
        max_length: Maximum generated character count.

    Returns:
        Generated number.

    Raises:
        ValueError: If no valid number can be generated.
    """
    generated: list[str] = []
    context = context_ids.copy()
    token_id_to_character = {
        token_id: character
        for character, token_id in digit_tokens.items()
    }

    while len(generated) < max_length:
        logits = model.get_logits_from_input_ids(context)
        free_token = choose_next_token_id(logits)
        has_digit = any(character.isdigit() for character in generated)

        if free_token not in token_id_to_character and has_digit:
            break

        allowed_characters = get_allowed_number_characters(generated)
        allowed_token_ids = [
            digit_tokens[character]
            for character in allowed_characters
            if character in digit_tokens
        ]
        next_token = choose_next_token_id(logits, allowed=allowed_token_ids)
        generated.append(token_id_to_character[next_token])
        context.append(next_token)

    if not any(character.isdigit() for character in generated):
        raise ValueError("could not generate a number argument")

    return parse_generated_number("".join(generated))


def generate_string(
        model: Any,
        context_ids: list[int],
        quote_tokens: set[int],
        max_length: int = 80,
) -> str:
    """Generate a JSON string value using constrained decoding.

    Args:
        model: LLM wrapper used for inference.
        context_ids: Token IDs that appear after the opening quote.
        quote_tokens: Token IDs that contain quote characters.
        max_length: Maximum generated token count.

    Returns:
        Generated string without surrounding quotes.
    """
    generated: list[int] = []
    context = context_ids.copy()

    while len(generated) < max_length:
        logits = model.get_logits_from_input_ids(context)
        free_token = choose_next_token_id(logits)

        if free_token in quote_tokens and generated:
            break

        allowed_token_ids = [
            token_id
            for token_id in range(len(logits))
            if token_id not in quote_tokens
        ]
        next_token = choose_next_token_id(logits, allowed=allowed_token_ids)
        generated.append(next_token)
        context.append(next_token)

    return cast(str, model.decode(generated).strip())


def encode_allowed_texts(
        allowed_texts: list[str],
        model: Any,
) -> list[list[int]]:
    """Encode allowed output strings into token ID sequences.

    Args:
        allowed_texts: Candidate strings that the decoder may generate.
        model: LLM wrapper used for tokenization.

    Returns:
        Token ID sequences for each allowed string.
    """
    return [
        get_input_ids(text, model)
        for text in allowed_texts
    ]


def choose_from_allowed_texts(
        prompt: str,
        allowed_texts: list[str],
        model: Any,
) -> str:
    """Choose one allowed text using constrained greedy decoding.

    Args:
        prompt: Prompt used as model context.
        allowed_texts: Candidate strings that may be generated.
        model: LLM wrapper used for inference and tokenization.

    Returns:
        Selected allowed text.

    Raises:
        ValueError: If no allowed text is provided or decoding gets stuck.
    """
    if not allowed_texts:
        raise ValueError("allowed texts must not be empty")

    allowed_token_ids = encode_allowed_texts(allowed_texts, model)
    generated_tokens: list[int] = []
    prompt_tokens = get_input_ids(prompt, model)

    while generated_tokens not in allowed_token_ids:
        possible_next_tokens = []

        for token_ids in allowed_token_ids:
            if token_ids[:len(generated_tokens)] == generated_tokens:
                if len(token_ids) > len(generated_tokens):
                    possible_next_tokens.append(
                        token_ids[len(generated_tokens)]
                    )

        if not possible_next_tokens:
            raise ValueError("no valid next token available")

        logits = model.get_logits_from_input_ids(
            prompt_tokens + generated_tokens
        )
        next_token_id = choose_next_token_id(
            logits,
            allowed=possible_next_tokens,
        )
        generated_tokens.append(next_token_id)

    return cast(str, model.decode(generated_tokens))


def generate_boolean(
        model: Any,
        context: str,
) -> bool:
    """Generate a JSON boolean using constrained decoding.

    Args:
        model: LLM wrapper used for inference and tokenization.
        context: Text that appears immediately before the boolean value.

    Returns:
        Boolean selected by the model from the valid JSON literals.
    """
    generated = choose_from_allowed_texts(
        context,
        ["true", "false"],
        model,
    )
    return generated == "true"


def build_function_selection_prompt(
        prompt: str,
        functions: list[FunctionDefinition],
) -> str:
    """Build a prompt for selecting the best function.

    Args:
        prompt: Natural-language request to classify.
        functions: Available function definitions.

    Returns:
        Prompt containing the request and available functions.
    """
    function_lines = [
        f"{function.name}: {function.description}"
        for function in functions
    ]

    return (
        "Select the best function for the user request.\n"
        "Available functions:\n"
        + "\n".join(function_lines)
        + f"\nUser request: {prompt}\n"
        "Function:"
    )


def choose_function(
        prompt: str,
        functions: list[FunctionDefinition],
        model: Any,
) -> FunctionDefinition:
    """Choose a function name for a prompt using constrained decoding.

    Args:
        prompt: Natural-language request to convert into a function call.
        functions: Available function definitions.
        model: LLM wrapper used for inference and tokenization.

    Returns:
        Selected function name.

    Raises:
        ValueError: If no function definitions are provided.
    """
    if not functions:
        raise ValueError("functions must not be empty")

    allowed_function_names = [
        f" {function.name}"
        for function in functions
    ]

    selection_prompt = build_function_selection_prompt(prompt, functions)
    selected_name = choose_from_allowed_texts(
        selection_prompt,
        allowed_function_names,
        model,
    ).strip()

    for function in functions:
        if function.name == selected_name:
            return function

    raise ValueError("selected function was not found")
